name = "yichen-crm-api"
main = "worker/worker.ts"
compatibility_date = "2026-04-06"

[[d1_databases]]
binding = "DB"
database_name = "yichen-crm"
database_id = "6943aae2-e0d7-40af-99dd-b8eb5f29b93f"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "yichen-crm-assets"
